#!/bin/bash

clear
echo "🧠⚡ SyntaxRush - Color Theme Showcase"
echo "====================================="
echo ""
echo "✨ Enhanced Color Scheme Applied:"
echo ""
echo "🎨 Color Mapping:"
echo "   📺 Background:     #1e1e1e (Dark Gray)"
echo "   ✅ Correct Chars:  #00FF88 (Neon Green)" 
echo "   ❌ Wrong Chars:    #FF5555 (Red)"
echo "   🟡 Current Line:   #FFD700 (Gold)"
echo "   📊 Timer/WPM:      #00BFFF (Cyan)"
echo "   📝 Static Text:    #AAAAAA (Light Gray)"
echo ""
echo "🚀 Features:"
echo "   • Beautiful ASCII art welcome screen"
echo "   • Enhanced contrast for better visibility"
echo "   • Consistent color scheme throughout"
echo "   • Eye-friendly dark theme optimized for coding"
echo ""
echo "▶️  Launch SyntaxRush to see the improvements:"
echo "   ./syntaxrush"
echo ""
echo "🎯 Try the file upload feature:"
echo "   1. Press Ctrl+U"
echo "   2. Type 'py' for Python sample"
echo "   3. Start typing and see the colors!"
